### ISSUE TITLE
Need a web.config

### ISSUE THREAD

**Issue by aarongustafson** [maxday/10k#1]
Template for Node: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by maxday** [comment]
Hi !
I've just added the missing file + tested the deployment here : http://10kolors.azurewebsites.net/
Everything should be fine
Thanks

**Comment by maxday** [comment]
Closing since https://10-kolors-a-10kapart-proj-10kapart2016.azurewebsites.net is correctly deployed
